import Head from "next/head";
import Image from "next/image";
import Title from "../components/Title";
import Article from "../components/Article";
import FoldingArticle from "../components/FoldingArticle";
import Menu from "../components/Menu";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="p-12">
        <Title />
        <FoldingArticle />
      </main>

      <footer></footer>
    </div>
  );
}
